sonata_core:
    form:
        mapping:
            enabled: false

sonata_block:
    default_contexts: [] # this line can be removed for sonata-project/block-bundle >= 3.10.0
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]
        sonata.admin.block.search_result:
            contexts: [admin]

sonata_admin:
    templates:
        list: 'admin/list.html.twig'